# Generated by Django 4.2.4 on 2023-11-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ManyToManyField(related_name='replers', to='boards.comment'),
        ),
    ]
