# Generated by Django 4.2.4 on 2023-11-20 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="depositproduct",
            name="sub_user",
        ),
        migrations.RemoveField(
            model_name="savingproduct",
            name="sub_user",
        ),
    ]
