# Generated by Django 4.2.4 on 2023-11-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingproduct',
            name='fin_prdt_cd',
            field=models.TextField(),
        ),
    ]
